LONG_CAPTCHA_ATTRIBUTE(noise_length, NOISE_LENGTH, 2, check_zero_or_positive_attribute)
LONG_CAPTCHA_ATTRIBUTE(challenge_length, CHALLENGE_LENGTH, 8, check_challenge_length_attribute)
LONG_CAPTCHA_ATTRIBUTE(fake_characters_color, FAKE_CHARACTERS_COLOR, 0, check_color_attribute)
LONG_CAPTCHA_ATTRIBUTE(fake_characters_length, FAKE_CHARACTERS_LENGTH, 2, check_fake_characters_length_attribute)
LONG_CAPTCHA_ATTRIBUTE(significant_characters_color, SIGNIFICANT_CHARACTERS_COLOR, 0, check_color_attribute)

STRING_CAPTCHA_ATTRIBUTE(session_prefix, SESSION_PREFIX, "captcha_", NULL)
STRING_CAPTCHA_ATTRIBUTE(html_wrapper_id, HTML_WRAPPER_ID, "captcha", NULL)
STRING_CAPTCHA_ATTRIBUTE(html_letter_tag, HTML_LETTER_TAG, "span", NULL)
STRING_CAPTCHA_ATTRIBUTE(html_wrapper_tag, HTML_WRAPPER_TAG, "div", NULL)
STRING_CAPTCHA_ATTRIBUTE(fake_characters_style, FAKE_CHARACTERS_STYLE, "display: none", NULL)
STRING_CAPTCHA_ATTRIBUTE(significant_characters_style, SIGNIFICANT_CHARACTERS_STYLE, "", NULL)
